name: CI

on: push

jobs:
  commit-lint:
    runs-on: self-hosted
    steps:
      - run: echo "in commit-lint" step

  core-test:
    needs: commit-lint
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        test-path:
          - tests/integration/multimodal/
          - tests/integration/optimizers/
          - tests/integration/ref_indexer/
          - tests/integration/sharding/
          - tests/unit/clients/
          - tests/unit/docker/
          - tests/unit/drivers/
    steps:
      - uses: actions/checkout@v2
      - name: Test
        id: test
        run: |
          echo "starting"
          echo "1"
          echo "2"
          echo "3"
          echo "4"
          echo "${{ matrix.test-path }}"
